pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'pip3 install -r s05/python-simple-app/requirements.txt'
                sh 'docker build -t apppysimple .'
            }
        }
        stage('run') {
            steps {
                sh 'python3 s05/python-simple-app/app.py &'
            }
        }

    /*     stage('') {
            steps {
                sh 'sleep 60 && curl -s localhost:8000'
            }
        }

        stage('cleanup') {
            steps {
                sh 'fuser -k 8000/tcp'
            }
    */    

    }
}